### ISSUE TITLE
Repo not working?

### ISSUE THREAD

**Issue by Zogproof** [fluxer/katana-freebsd#1]
The /usr/local/etc/pkg/repos/ dir already exists.

# echo 'Katana: { url: "pkg+https://raw.githubusercontent.com/fluxer/katana-freebsd/master", mirror_type: "srv", enabled: yes }' > /usr/local/etc/pkg/repos/Katana.conf

# pkg update
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
Updating Katana repository catalogue...
pkg: No SRV record found for the repo 'Katana'
Fetching meta.conf: 100%    163 B   0.2kB/s    00:01    
pkg: packagesite URL error for pkg+https://raw.githubusercontent.com/fluxer/katana-freebsd/master/packagesite.pkg -- pkg+:// implies SRV mirror type
pkg: packagesite URL error for pkg+https://raw.githubusercontent.com/fluxer/katana-freebsd/master/packagesite.txz -- pkg+:// implies SRV mirror type
Unable to update repository Katana
Error updating repositories!

Maybe something at my end, I guess.

**Comment by fluxer** [comment]
Probably FreeBSD broke something. Forunately, the repository is a git repository meaning cloning it and installing the packages via `pkg` is always an option so install the packages manually, I will look into it when I can.

**Comment by fluxer** [comment]
Works for me, tested it in virtual machine running v13.2 which is the FreeBSD version the packages are for.

**Comment by fluxer** [comment]
Closing, you will have to figure out what went wrong.
